import type { Metadata } from "next";
import "./styles/globals.css";
import "./styles/reset.css";
import "./styles/normalice.css";
import { monserratLight } from "./fonts";

export const metadata: Metadata = {
  title: "Almacen surtillantas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={monserratLight.className}>{children}</body>
    </html>
  );
}
